### ISSUE TITLE
@figspec/react is included in the published source but not the package.json

### ISSUE THREAD

**Issue by lukeapage** [pocka/storybook-addon-designs#85] opened 2021-02-22 12:59 UTC
Imported in code:
https://github.com/pocka/storybook-addon-designs/blob/release/v6.0/packages/storybook-addon-designs/src/register/components/Figspec.tsx#L14

but on present in dev dependencies:
https://github.com/pocka/storybook-addon-designs/blob/release/v6.0/packages/storybook-addon-designs/package.json#L22

Is this intentional?

Broke my build until I added a dependencies myself to the root.

**Comment by pocka** [comment] 2021-02-23 10:12
Duplicate of #80

**Comment by pocka** [comment] 2021-02-23 11:01
Never mind, we should specify it as [externals](https://webpack.js.org/configuration/externals/) or mark it as a regular dependency.

**Comment by lukeapage** [comment] 2021-02-23 15:45
Ok, it just wasn’t clear in the documentation or maybe I missed it. If it was in the first 2 lines of the reader I would have just added it.

**Comment by pocka** [comment] 2021-02-23 16:28
The problem is "build is broken due to missing dependency even the project does not use `type: "experimental-figspec"`, isn't it? Then it's unintentional.
If it is "build is broken only when the project uses `type: "experimental-figspec"` instead, then it's intentional behaviour. However I agree that the document is not enough clear, we probably should have an indication of the additional requirements in `README.md` or a [Quick Start page](https://storybook-addon-designs-rhgclupaa.vercel.app/?path=/story/docs-quick-start--page) until stable release.

**Comment by fredjiles** [comment] 2021-02-23 16:35
It was broken for me and I am not using figspec.  I just installed the package, enabled the plugin, and started storybook and got the error.

**Comment by pocka** [comment] 2021-02-23 16:47
@fredjiles 
Thanks for the report!
I just forgot the details of dynamic import in webpack at the time of implementing the feature. I'll add the package as a regular dependency in the next alpha release (probably until 2020-02-24T22:00:00+09:00) as a quick fix. Then fix the module loading and revert the previous patch.

**Comment by lukeapage** [comment] 2021-02-23 17:39
Yes that’s right we are not using that type.

it works during watch and errors when we build ..

**Comment by pocka** [comment] 2021-02-24 04:07
Fixed in v6.0.0-alpha.3

**Closed by pocka** 2021-02-24 04:07 UTC
Labels: bug
